[package]
name = "xtask"
license = "BSD-3-Clause"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
xshell = "0.2.7"
xray = { path = "../xray" }
