name: CI
on: [push, pull_request]
permissions: {}

jobs:
  trigger:
    if: |
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
      )
    runs-on: ubuntu-24.04
    steps:
    - name: CI Trigger
      run: echo "Triggering CI"

  linters:
    needs: trigger
    uses: ./.github/workflows/linters.yml

  coverage:
    needs: trigger
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      run: rustup update stable
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Generate code coverage
      run: |
        sudo apt-get install -y libpcap-dev
        cargo xtask code-coverage --context ci
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: lcov.info
        fail_ci_if_error: true

  tests:
    needs: trigger
    uses: ./.github/workflows/tests.yml

  check-all-green:
    needs:
    - linters
    - tests
    - coverage
    runs-on: ubuntu-24.04
    steps:
    - name: Collect statuses from all jobs
      uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
      with:
        jobs: ${{ toJSON(needs) }}
